---

- name: Package installation
  apt: name=nginx update_cache=yes state=latest

- include_role:
    name: nginx-hardening

- name: Disable nginx SSL Settings
  replace: dest=/etc/nginx/nginx.conf regexp={{ item.regexp }} replace={{ item.replace }} backup=true
  with_items:
    - { regexp: 'ssl_protocols', replace: '# ssl_protocols' }
    - { regexp: 'ssl_prefer_server_ciphers', replace: '# ssl_prefer_server_ciphers' }

- name: Block bad bots
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
    - { url: "https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blacklist.conf", dest: /etc/nginx/conf.d/blacklist.conf }
    - { url: "https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blockips.conf", dest: /etc/nginx/conf.d/blockips.conf }
