---

- name: Add backports repository
  apt_repository:
    repo: deb http://mirrors.digitalocean.com/debian {{ ansible_lsb.codename }}-backports main
    state: present

- name: Package installation
  apt: name=nginx update_cache=yes state=latest default_release={{ ansible_lsb.codename }}-backports

- include_role:
    name: nginx-hardening

- name: Remove nginx directives to fix nginx-hardening conflicts
  lineinfile: dest=/etc/nginx/nginx.conf regexp={{ item.regexp }} state=absent backup=true
  with_items:
    - { regexp: 'ssl_protocols' }
    - { regexp: 'ssl_prefer_server_ciphers' }

- name: Block bad bots
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
    - { url: "https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blacklist.conf", dest: /etc/nginx/conf.d/blacklist.conf }
    - { url: "https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blockips.conf", dest: /etc/nginx/conf.d/blockips.conf }
