---
- name: Installation
  hosts: '{{ target }}'
  vars:
      user: admin
      disallow_root_login: false
      execute_firewall: false
      manala_motd_template: "{{ playbook_dir ~ '/templates/motd.j2' }}"
      fail2ban_services:
          - name: ssh
            port: 22
            maxretry: 5
            bantime: -1

  roles:
      - apt
      - user
      - motd
      - iptables
      - fail2ban
      - { role: docker, when docker.stat.exists == false }
...
