---

- name: Installation
  hosts: all
  vars_files:
    - vars/main.yml

  roles:
    - apt
    - motd
    - firewall
    # - fail2ban
    - nodejs
    - unattended-upgrades
    - nginx-modsecurity
    - docker
    - dokku # NOTICE: Keep this role after nginx and docker roles
    - ssh-hardening
    - os-hardening
    - user # NOTICE: Keep this role after ssh-hardening
...
