---
- name: Installation
  hosts: '{{ target }}'
  vars_files:
    - vars/main.yml

  roles:
    - apt
    - user
    - motd
    - firewall
    - fail2ban
    - os-hardening
    - { role: docker, when docker.stat.exists == false }
...
