---
- name: Installation
  hosts: '{{ target }}'
  vars_files:
    - vars/main.yml

  roles:
    - apt
    - motd
    - firewall
    - fail2ban
    - unattended-upgrades
    - docker
    - nginx
    - ssh-hardening
    - os-hardening
    - user # NOTICE: Keep this role after ssh-hardening
...
