---
- name: Create {{ user }} user
  user: name={{ user }} shell=/usr/bin/zsh groups=sudo,users
- name: Add ssh key to {{ user }} user
  authorized_key: user={{ user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: Add {{ user }} to sudoers
  template: src=templates/sudoers.j2 dest=/etc/sudoers.d/{{ user }}-sudoer validate='visudo -cf %s'
