---

- stat:
    path: /usr/bin/docker
  register: docker

- block:
    - name: install apt-transport-https
      apt: name=apt-transport-https

    - apt_key: url=https://packagecloud.io/gpg.key state=present

    - name: Add dokku repository
      apt_repository: repo="deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main" state=present

    - shell: echo "dokku dokku/web_config boolean false" | debconf-set-selections
    - shell: echo "dokku dokku/skip_key_file boolean true" | debconf-set-selections

    - name: Install dokku
      apt: name=dokku update_cache=true state=latest

    - name: Remove nginx directives to fix dokku conflicts
      lineinfile: dest={{ item.dest }} regexp={{ item.regexp }} state=absent backup=true
      with_items:
        - { dest: /etc/nginx/conf.d/dokku.conf, regexp: 'server_tokens' }
        - { dest: /etc/nginx/conf.d/dokku.conf, regexp: 'ssl_ciphers' }
        - { dest: /etc/nginx/conf.d/90.hardening.conf, regexp: 'nosniff' }

    - shell: dokku plugin:install https://github.com/dokku/dokku-redirect.git || true
      ignore_errors: true

    - shell: dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git || true
      ignore_errors: true

    - shell: dokku plugin:install https://github.com/dokku/dokku-mysql.git || true
      ignore_errors: true

    - shell: dokku plugin:install https://github.com/dokku/dokku-mongo.git || true
      ignore_errors: true

  when: docker.stat.exists
