---

- stat:
    path: /usr/sbin/nginx
  register: nginx

- block:
    # Dependencies

    - name: Add backports repository
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_lsb.codename }}-backports main
        state: present

    - name: Build nginx dependencies
      apt: pkg=nginx state=build-dep

    - name: Install dependencies
      apt: name={{ item }} update_cache=yes state=latest default_release={{ ansible_lsb.codename }}-backports
      with_items:
        - git
        - libcurl4-openssl-dev
        - apache2-dev
        - libtool
        - autoconf
        - libhiredis-dev
        - libssl-dev
        - quilt

    # Modsecurity

    - name: Git clone modsecurity
      git: repo=https://github.com/SpiderLabs/ModSecurity dest=/opt/modsecurity version=v3/master update=no

    - name: Build modsecurity
      shell: cd /opt/modsecurity/ && ./build.sh && ./configure && make && make install

    - name: Git clone modsecurity-nginx
      git: repo=https://github.com/SpiderLabs/ModSecurity-nginx dest=/opt/modsecurity-nginx update=no

    # Nginx

    - name: Git clone nginx
      git: repo=https://anonscm.debian.org/cgit/pkg-nginx/nginx.git dest=/opt/nginx version={{ ansible_lsb.codename }}-backports update=no

    - replace: dest=/opt/nginx/debian/rules regexp='\./configure \$' replace='./configure --add-module=/opt/modsecurity-nginx $'

    - name: Override nginx config
      shell: grep override_dh_shlibdeps /opt/nginx/debian/rules || echo '\noverride_dh_shlibdeps:\n\tdh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info' >> /opt/nginx/debian/rules

    - name: Install nginx packages
      shell: cd /opt/nginx && dpkg-buildpackage -b && dpkg -i /opt/nginx-common_*.deb /opt/libnginx-mod-*.deb /opt/nginx-full_*.deb /opt/nginx_*.deb

    # Enable modsecurity

    - shell: cp /opt/modsecurity/modsecurity.conf-recommended /etc/nginx/modsecurity.conf
    - replace: dest=/etc/nginx/modsecurity.conf regexp='^\s*SecRuleEngine DetectionOnly' replace='SecRuleEngine On'
    - replace:
        dest: /etc/nginx/nginx.conf
        regexp: 'http \{'
        replace: 'http {\n\tmodsecurity on;\n\tmodsecurity_rules_file /etc/nginx/modsecurity.conf;'
        backup: true

    # Install owasp rules

    - name: Git clone owasp
      git: repo=https://github.com/SpiderLabs/owasp-modsecurity-crs.git dest=/opt/owasp update=no

    - shell: cp -r /opt/owasp/rules/ /etc/nginx/
    - shell: cp /opt/owasp/crs-setup.conf.example /etc/nginx/crs-setup.conf
    - shell: echo 'Include crs-setup.conf' >> /etc/nginx/modsecurity.conf
    - shell: echo 'Include rules/*.conf' >> /etc/nginx/modsecurity.conf

    # Cleanup

    - shell: rm -f /opt/*.deb /opt/*.changes /opt/*.buildinfo

    # Prevent nginx update

    - shell: apt-mark hold nginx nginx-full

    # Nginx-hardening

    - include_role:
        name: nginx-hardening

    - name: remove nginx directives to fix nginx-hardening conflicts
      lineinfile: dest=/etc/nginx/nginx.conf regexp={{ item.regexp }} state=absent
      with_items:
        - { regexp: 'ssl_protocols' }
        - { regexp: 'ssl_prefer_server_ciphers' }

    # Bad bots

    - name: block bad bots
      get_url: url={{ item.url }} dest={{ item.dest }}
      with_items:
        - { url: "https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blacklist.conf", dest: /etc/nginx/conf.d/blacklist.conf }
        - { url: "https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blockips.conf", dest: /etc/nginx/conf.d/blockips.conf }

    - name: Enable default website
      file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link

  when: not nginx.stat.exists
