---

- stat:
    path: /usr/bin/docker
  register: docker

- name: install apt-transport-https
  apt:
    name: apt-transport-https
  when: not docker.stat.exists

- apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  when: not docker.stat.exists
  retries: 2

- apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-{{ ansible_lsb.codename }} main
  when: not docker.stat.exists

- name: Install list of packages
  apt: name={{item}} state=installed
  when: not docker.stat.exists
  with_items:
    - ca-certificates
    - gnupg2
    - docker-engine
