---

- stat:
    path: /usr/bin/docker
  register: docker

- block:
    - name: install apt-transport-https
      apt:
        name: apt-transport-https

    - apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
      retries: 2

    - apt_repository:
        repo: deb https://apt.dockerproject.org/repo debian-{{ ansible_lsb.codename }} main

    - name: Install docker
      apt: name={{ item }} state=installed
      with_items:
        - ca-certificates
        - gnupg2
        - docker-engine
  when: not docker.stat.exists
